### ISSUE TITLE
Warnings from GHA

### ISSUE THREAD

**Issue by henryiii** [jwlawson/actions-setup-cmake#11]
Using the action causes a lot of warning to appear. The solution is to upgrade actions/core to 1.2.6, which has already been done AFAICT, but is not in a released version. Can this be updated? Either a v1.3.1 with v1.3 now pointing at that, or v1.4, etc. Thanks!

Warning produced:
```
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by jwlawson** [comment]
I've pushed a v1.4 [tag and release](https://github.com/jwlawson/actions-setup-cmake/releases/tag/v1.4). Thanks for the bringing this up.

**Comment by henryiii** [comment]
Fantastic, really appreciate it! Great action, by the way. I mention it in [Modern CMake](https://cliutils.gitlab.io/modern-cmake/chapters/intro/installing.html#ci).
