### ISSUE TITLE
Arch directory issue for 3.19.3

### ISSUE THREAD

**Issue by henryiii** [jwlawson/actions-setup-cmake#18]
There's a problem with 3.19.3 that causes an aarch executable to be used. See https://github.com/pybind/pybind11/pull/2790 and https://github.com/pybind/pybind11/pull/2756. Haven't looked into it in detail yet.

**Comment by jwlawson** [comment]
Looks like 3.19.3 introduces the aarch64 packages, which were not handled correctly in the package parsing logic. The merged PR above should fix this, and I'm just working on pushing a new release that includes it.

**Comment by jwlawson** [comment]
Can you test this with v1.6 and see if it works correctly?

**Comment by henryiii** [comment]
Looks like it's working! (there are two failures there from Python 3.10a4, those are unrelated and will be stuck there till 3.10a5; the cmake part is working)
