### ISSUE TITLE
Older versions not discoverable.

### ISSUE THREAD

**Issue by henryiii** [jwlawson/actions-setup-cmake#21]
Older versions of CMake are reporting that they are not found. 3.4-3.8 are not working, while 3.18 is fine. Broken on both 1.5 and 1.6; it used to be working so maybe the API this is using changed the way it reports?

I think loading multiple pages is broken, only releases on page 1 are now accessible, perhaps? I don't see anything different [here](https://docs.github.com/en/rest/reference/repos#list-releases--code-samples), and by hand it seems to be fine.

See https://github.com/pybind/pybind11/pull/2805.

**Comment by henryiii** [comment]
Actually, https://api.github.com/repos/Kitware/cmake/releases works but https://api.github.com/repos/Kitware/cmake/releases&page=1 does not.

**Comment by Holzhaus** [comment]
I see the same on 3.13.x:

```
Run jwlawson/actions-setup-cmake@v1.4
Error: Unable to find version matching 3.13.x
```
https://github.com/mixxxdj/mixxx/runs/1724308441

I didn't touch the CI config and I'm sure this worked yesterday.

**Comment by archurcode** [comment]
the same on 3.10.2:
Unable to find version matching 3.10.2

**Comment by alkino** [comment]
If you look at your both links @henryiii they seems to only report version > 3.17

**Comment by alkino** [comment]
I think the github API is broken.
There is no more `Link:` header. So the module cannot guess there is new pages to look for.

**Comment by alkino** [comment]
In fact @henryiii already report it: https://github.community/t/bug-rest-api-for-releases-missing-link/156320

**Comment by henryiii** [comment]
Sorry, I've been debugging in the linked PR, should have been posting here I guess.

**Comment by jwlawson** [comment]
I've managed to have a quick look into this. It does seem that something weird is going on with the GitHub API.

Trying Octokit gives the same failures, as it seems to also use the Link header for pagination.

Manually going back through the release JSON pages, I can only see results up to https://api.github.com/repos/kitware/cmake/releases?page=5 (with 3.12.4 as the last visible release). Then https://api.github.com/repos/kitware/cmake/releases?page=6 returns no results, even though https://github.com/Kitware/CMake/releases?after=v3.12.4 still shows the old releases. So even iterating through the pages like that won't work currently.

**Comment by henryiii** [comment]
I don't think they are ordered by number, but by date. I'm pretty sure the older releases were on page 4 or 5, there are just also newer releases too. Can check later.

**Comment by henryiii** [comment]
I see at least 3.7 on page 4. When they started the mirror, all the early releases got added at the same time. So I think pagination is fine, just that header is missing.

**Comment by henryiii** [comment]
This is the current list of versions if you just load the first 5 pages, in order they are presented:

Page 1: v3.19.3 v3.19.2 v3.19.1 v3.19.0 v3.18.5 v3.19.0-rc3 v3.19.0-rc2 v3.19.0-rc1 v3.18.4 v3.18.3 v3.17.5 v3.16.9 v3.18.2 v3.18.1 v3.17.4 v3.18.0 v3.18.0-rc4 v3.18.0-rc3 v3.18.0-rc2 v3.18.0-rc1 v3.16.8 v3.17.3 v3.16.7 v3.17.2 v3.16.6 v3.17.1 v3.17.0 v3.17.0-rc3 v3.16.5 v3.17.0-rc2
Page 2: v3.17.0-rc1 v3.16.4 v3.15.7 v3.16.3 v3.16.2 v3.15.6 v3.16.1 v3.16.0 v3.16.0-rc4 v3.16.0-rc3 v3.15.5 v3.16.0-rc2 v3.16.0-rc1 v3.14.7 v3.15.4 v3.15.3 v3.15.2 v3.15.1 v3.15.0 v3.14.6 v3.15.0-rc4 v3.15.0-rc3 v3.15.0-rc2 v3.15.0-rc1 v3.14.5 v3.14.4 v3.13.5 v3.14.3 v3.14.2 v3.14.1
Page 3: v3.14.0 v3.14.0-rc4 v3.14.0-rc3 v3.14.0-rc2 v3.14.0-rc1 v3.13.4 v3.13.3 v3.13.2 v2.4.8 v2.6.4 v2.8.12.2 v2.8.10.2 v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.1.1 v3.1.2 v3.1.3 v3.2.0 v3.2.1 v3.2.2 v3.2.3 v3.3.0 v3.3.2 v3.4.1 v3.4.2 v3.6.2 v3.6.3 v3.7.0
Page 4: v3.9.1 v3.9.2 v3.9.3 v3.9.5 v3.3.1 v3.4.0 v3.4.3 v3.5.0 v3.5.1 v3.5.2 v3.6.0 v3.6.1 v3.7.1 v3.7.2 v3.8.0 v3.8.1 v3.8.2 v3.9.0 v3.9.4 v3.9.6 v3.10.0 v3.10.1 v3.10.2 v3.10.3 v3.11.0 v3.11.1 v3.11.2 v3.11.3 v3.11.4 v3.12.0
Page 5: v3.12.1 v3.12.2 v3.12.3 v3.13.1 v3.13.0 v3.12.4

So they are all there, I think. It's 126 releases, so must be less than 100 per page.

**Comment by jwlawson** [comment]
Oh right. Thanks. I made some changes to just iterate through the pages in #23 without relying on the Link header.

**Comment by lewri** [comment]
Just passing note -- appears this is working now for CMake 3.5, using in CorsixTH's gh-actions.

**Comment by henryiii** [comment]
Solved by GitHub in 1-2 days, pagination works again. :tada:
