### ISSUE TITLE
CMake 3.20.0-rc1 breaks action

### ISSUE THREAD

**Issue by YannickJadoul** [jwlawson/actions-setup-cmake#27]
Currently, CMake's 3.20.0-rc1 release breaks the usage of `actions-setup-cmake` when no CMake version is pinned, with the following error message:

```
Run jwlawson/actions-setup-cmake@v1.7
Error: Could not find linux asset for cmake version 3.20.0
```

One of the issues might be that [this 3.20.0-rc1 release](https://github.com/Kitware/CMake/releases/tag/v3.20.0-rc1) isn't tagged on GitHub releases as prerelease (as I believe this action would normally ignore such prerelease?). However, the resulting error is still unexpected, as I had expected `actions-setup-cmake` would just install that version. But apparently that's not the case?

**Comment by YannickJadoul** [comment]
Oh, another reason I'm reporting this, and not just blaming CMake's bad release is because things do seem to work for macOS:

```
Run jwlawson/actions-setup-cmake@v1.7
Warning: Found 2 matching packages.
```

Unfortunately, I can't really figure out which CMake version gets installed from the logs. But a version (either 3.19.5 or 3.20.0-rc1, I presume?) does get installed. So either there's an issue where the 3.20.0-rc1 Linux & Windows versions don't get picked up but do get picked up on macOS; or macOS is not at all picking up on the 3.20.0-rc1 release. Either way, this seems to be an inconsistency, possibly pointing towards a bug?

**Comment by YannickJadoul** [comment]
Apologies! Looking at the code, the non-prerelease status of 3.20.0-rc1 might be a red herring.

It seems CMake changed the filenames from `cmake-3.19.5-Linux-x86_64.tar.gz` to `cmake-3.20.0-rc1-linux-x86_64.tar.gz` and from `cmake-3.19.5-win64-x64.zip` to `cmake-3.20.0-rc1-windows-x86_64.zip`.

That being said, `-rc1` being installed is still a bit of an issue, perhaps. But not really anything to blame on `actions-setup-cmake`.

**Comment by jwlawson** [comment]
Thanks for looking into this. It does look like the package renaming is the problem, and should be fixed in #28.

We could definitely filter out names containing `rc[0-9]` as a workaround for any not marked as prerelease.

**Comment by YannickJadoul** [comment]
Thanks a lot! That was very fast :-)

**Comment by YannickJadoul** [comment]
> We could definitely filter out names containing `rc[0-9]` as a workaround for any not marked as prerelease.

Up to you, by the way; I currently don't mind if things install correctly, but I thought it was worth reporting, even though it turned out not to be the cause of the issues.
