### ISSUE TITLE
Potential change

### ISSUE THREAD

**Issue by henryiii** [jwlawson/actions-setup-cmake#31]
Just a warning, 3.20 was just released and contains a renaming of Linux and Windows binaries. Probably should rerun the tests to make sure 3.20 is picked up properly. :)

**Comment by jwlawson** [comment]
A very late thanks for the heads up. It looks like everything's working OK for 3.20 and beyond, and we have [nightly builds](https://github.com/jwlawson/actions-setup-cmake/actions/workflows/nightly.yml) monitoring for breaking changes.
