### ISSUE TITLE
Add support for 32 bit CMake

### ISSUE THREAD

**Issue by PibePlayer** [jwlawson/actions-setup-cmake#32]
My forked project needs the 32 bit version of CMake to build :)

**Comment by jwlawson** [comment]
Thanks for the suggestion. I had some time today to add a `use-32bit` option for this in #33. This is now available in version 1.9 if you want to try it out.

**Comment by PibePlayer** [comment]
Cool! Already using it on my project, future-proof I'll say to other people that went from a manual approach to this action:
Don't forget to redo the build cache since it'll search the cmake binary in the wrong location otherwise

**Comment by aminya** [comment]
This should be closed as it is already fixed.
