### ISSUE TITLE
Archive fails to unpack on windows server 2016 self hosted runner

### ISSUE THREAD

**Issue by sensor-todd** [jwlawson/actions-setup-cmake#44]
I am running into an issue when running actions-setup-cmake on windows server 2016 where powershell fails on Expand-Archive because it appears the '.zip' extension is missing from the command, giving the result:

Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:2[10](https://github.com/xxxxxxxxxxxx/xxxxxxxxxxxx/runs/xxxxxxxxxxxx?check_suite_focus=true#step:7:10)
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\xxxxxxxxx\ac ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive

I am new to self-hosted runners, is this a bug or a fault in my configuration?

**Comment by jwlawson** [comment]
I don't have any experience with self-hosted runners so am of limited help. The extraction is handled by [tool-cache](https://github.com/actions/toolkit/tree/main/packages/tool-cache) (see [here](https://github.com/jwlawson/actions-setup-cmake/blob/884cf5c591490f86b788d68b6f585f26235578d6/src/setup-cmake.ts#L59)) so I don't think there's much we can do here to work around it.

There have been some discussions in other projects (e.g. [google cloud](https://github.com/google-github-actions/setup-gcloud/issues/401#issuecomment-1001242895)) about similar errors that have some suggestions to try installing `pwsh` as that will be used by tool-cache over powershell (see [here](https://github.com/actions/toolkit/blob/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca/packages/tool-cache/src/tool-cache.ts#L350-L395)). The github hosted runners are using pwsh so maybe that's the way forward?

For reference, the command run by this project's nightly on windows looks to be:
```
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "
$ErrorActionPreference = 'Stop' ; 
try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; 
try { 
    [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\...5c9572', 'D:\...336bfdc', $true) 
} catch {
     if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ 
        Expand-Archive -LiteralPath 'D:\...5c9572' -DestinationPath 'D:\...336bfdc' -Force 
    } else { 
        throw $_ 
    }
} ;"
```

**Comment by sensor-todd** [comment]
Thanks will try out the suggestions in the link you have provided and edit this comment with the results.

**Comment by sensor-todd** [comment]
Installing Powershell 7 (pwsh) and, importantly, restarting the self-hosted runner service on the server machine got everything working. Thanks for the pointer John!
