### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by rwgk** [jwlawson/actions-setup-cmake#65]
I'm seeing warnings like:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jwlawson/actions-setup-cmake@v1.14. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

For example here: https://github.com/google/pywrapcc/actions/runs/7663060547

Is this already on your radar? The jobs finish fine, but the many warnings are easily distracting.

The corresponding GHA yml:

https://github.com/google/pywrapcc/blob/82d782474e8e43359dc95c282f1fa9b4ac2bb1bb/.github/workflows/ci.yml

**Comment by jwlawson** [comment]
Thanks for bringing this to my attention, I wasn't aware. Big thanks to @joshstrohminger for looking into resolving this too.
